#!/usr/bin/env python3
"""
Generates Prover.toml for the age_credential Noir circuit.

The "issuer" (e.g. a government) holds a secp256k1 key pair.
They sign blake2s(birth_year_big_endian) to attest to a person's birth year.
The prover uses this signature as a private input to the ZKP circuit.
"""

import hashlib
import struct
import sys
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
from cryptography.hazmat.primitives.asymmetric import utils as asym_utils
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend

# --- Configuration ---
BIRTH_YEAR   = 1987
CURRENT_YEAR = 2026
REQUIRED_AGE = 18

# Fixed issuer private key (hex) -- for demo reproducibility.
# In production this would be the government's secret key.
ISSUER_PRIVATE_KEY_INT = 0xB94F5374FEB0F494F9A9B7A9DCB71C5C56B79BF7B7C9C6A9E7B9F5F6C3A1E2D

# --- Compute message hash: blake2s(birth_year as big-endian u32) ---
year_bytes = struct.pack(">I", BIRTH_YEAR)          # 4 bytes, big-endian
msg_hash   = hashlib.new("blake2s", year_bytes, digest_size=32).digest()

# --- Generate issuer key pair and sign ---
private_key = ec.derive_private_key(
    ISSUER_PRIVATE_KEY_INT, ec.SECP256R1(), default_backend()
)
public_key = private_key.public_key()

# Sign the pre-computed hash (ECDSA with Prehashed)
sig_der = private_key.sign(msg_hash, ec.ECDSA(asym_utils.Prehashed(hashes.SHA256())))
r, s    = decode_dss_signature(sig_der)

# --- Extract raw bytes ---
sig_bytes   = r.to_bytes(32, "big") + s.to_bytes(32, "big")    # 64 bytes: r || s
pub_numbers = public_key.public_numbers()
pub_x_bytes = pub_numbers.x.to_bytes(32, "big")
pub_y_bytes = pub_numbers.y.to_bytes(32, "big")

# --- Helper: format bytes as a TOML array ---
def to_toml_array(b: bytes) -> str:
    return "[" + ", ".join(str(byte) for byte in b) + "]"

# --- Write Prover.toml ---
toml = f"""# Generated by generate_inputs.py
# Scenario: prove age >= {REQUIRED_AGE} without revealing birth_year

# Private inputs (known only to the prover)
birth_year     = {BIRTH_YEAR}
credential_sig = {to_toml_array(sig_bytes)}

# Public inputs (known to both prover and verifier)
current_year     = {CURRENT_YEAR}
required_age     = {REQUIRED_AGE}
issuer_pub_key_x = {to_toml_array(pub_x_bytes)}
issuer_pub_key_y = {to_toml_array(pub_y_bytes)}
"""

with open("Prover.toml", "w") as f:
    f.write(toml)

print(f"Prover.toml written.")
print(f"  birth_year   = {BIRTH_YEAR}")
print(f"  current_year = {CURRENT_YEAR}")
print(f"  age          = {CURRENT_YEAR - BIRTH_YEAR}  (>= {REQUIRED_AGE}: {CURRENT_YEAR - BIRTH_YEAR >= REQUIRED_AGE})")
print(f"  msg_hash     = {msg_hash.hex()}")
print(f"  sig r        = {r.to_bytes(32, 'big').hex()}")
print(f"  sig s        = {s.to_bytes(32, 'big').hex()}")
print(f"  pub_key_x    = {pub_x_bytes.hex()}")
print(f"  pub_key_y    = {pub_y_bytes.hex()}")
